version: '3'

services:
  www-nginx:
    container_name: portal2-www-nginx
    image: nginx:stable-alpine
    volumes:
      - ./www:/var/www/
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/:/etc/nginx/ssl/
      - ./log/:/var/log/nginx/
    links:
      - www-php
    networks:
      - rede_docker
    expose:
      - 443

  www-php:
    container_name: www-php
    build:
      context: php-fpm
    volumes:
      - ./www:/var/www/
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
    networks:
      - rede_docker

networks:
  rede_docker:
    external: true

