version: '3'
volumes:
  data:
services:
  www-apache:
    container_name: portal-www-apache
    build:
      context: ./apache
    restart: always
    expose:
      - "80"
    volumes:
      - ./www:/var/www/
      - ./apache/conf:/etc/apache2/sites-available/
      - ./ssl:/etc/apache2/ssl/
      - ./apache/files:/opt/oracle/
    networks:
      - rede_docker

networks:
  rede_docker:
    external: true